version: '3.8'

# Create networks:
networks:
  elsa-network:
    driver: bridge

services:
  elsa-db:
    image: postgres
    container_name: elsa-db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - elsa-network
    environment:
      - POSTGRES_USER=elsa_admin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=elsa_db


  elsa-redis:
    image: redis
    container_name: elsa-redis
    ports:
      - "6379:6379"
    networks:
      - elsa-network

  elsa-api:
    build: .
    container_name: elsa-api
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - elsa-db
      - elsa-redis
    networks:
      - elsa-network
    restart: always
    ports:
      - "8000:8000"

  elsa-nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api:/usr/src/api
    networks:
      - elsa-network
    depends_on:
      - elsa-api
