version: '3.8'

# Create networks:
networks:
  quiz-network:
    driver: bridge

# Create service:
services:
  quiz-db:
    image: postgres
    container_name: quiz-db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - quiz-network
    environment:
      - POSTGRES_USER=quiz_admin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=quiz_db

  quiz-redis:
    image: redis
    container_name: quiz-redis
    ports:
      - "6379:6379"
    networks:
      - quiz-network

  quiz-api:
    build: .
    container_name: quiz-api
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - quiz-db
      - quiz-redis
    networks:
      - quiz-network
    restart: always
    ports:
      - "8000:8000"

  quiz-nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api:/usr/src/api
    networks:
      - quiz-network
    depends_on:
      - quiz-api
