# Generated by Django 4.2.3 on 2024-11-09 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizsession_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='max_participants',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
